# Generated by Django 5.1.7 on 2025-03-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('A_ID', models.AutoField(primary_key=True, serialize=False)),
                ('A_NAME', models.CharField(max_length=50)),
                ('A_SURNAME', models.CharField(max_length=50)),
                ('A_PATRONYMIC', models.CharField(max_length=50)),
                ('A_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('A_TEL', models.CharField(max_length=30)),
                ('A_DATE', models.DateField()),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('E_ID', models.AutoField(primary_key=True, serialize=False)),
                ('E_NAME', models.CharField(max_length=50)),
                ('E_COUNT', models.IntegerField()),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Equipment_Type',
            fields=[
                ('T_TYPE', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('T_WEIGHT', models.DecimalField(decimal_places=2, max_digits=6)),
                ('T_HEIGHT', models.DecimalField(decimal_places=2, max_digits=4)),
                ('T_LENGTH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('T_WIDTH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('T_CAPACITY', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('T_LIFE', models.IntegerField()),
                ('T_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('L_ID', models.AutoField(primary_key=True, serialize=False)),
                ('L_SHOP', models.CharField(max_length=30)),
                ('L_AREA', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Management_Journal',
            fields=[
                ('J_ID', models.AutoField(primary_key=True, serialize=False)),
                ('J_DATETIME', models.DateTimeField()),
                ('J_TYPE', models.CharField(max_length=30)),
                ('A_ID', models.ForeignKey(db_column='A_ID', on_delete=django.db.models.deletion.CASCADE, to='api.administrator')),
            ],
            options={
                'db_table': 'management_journal',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('P_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'passport',
            },
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('R_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'search_result',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('U_ID', models.AutoField(primary_key=True, serialize=False)),
                ('U_NAME', models.CharField(max_length=50)),
                ('U_SURNAME', models.CharField(max_length=50)),
                ('U_PATRONYMIC', models.CharField(max_length=50)),
                ('U_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('U_TEL', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='equipment',
            name='T_TYPE',
            field=models.ForeignKey(db_column='T_TYPE', on_delete=django.db.models.deletion.CASCADE, to='api.equipment_type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='L_ID',
            field=models.ForeignKey(db_column='L_ID', on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AddField(
            model_name='management_journal',
            name='E_ID',
            field=models.ForeignKey(db_column='E_ID', on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AddField(
            model_name='passport',
            name='E_ID',
            field=models.OneToOneField(db_column='E_ID', on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AddField(
            model_name='passport',
            name='T_TYPE',
            field=models.ForeignKey(db_column='T_TYPE', on_delete=django.db.models.deletion.CASCADE, to='api.equipment_type'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='P_ID',
            field=models.OneToOneField(db_column='P_ID', on_delete=django.db.models.deletion.CASCADE, to='api.passport'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='E_ID',
            field=models.ForeignKey(db_column='E_ID', on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='U_ID',
            field=models.ForeignKey(db_column='U_ID', on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
    ]
