# Generated by Django 5.1.7 on 2025-04-22 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrator_equipment_equipment_type_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='A_DATE',
            field=models.DateField(db_column='a_date'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_EMAIL',
            field=models.CharField(db_column='a_email', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_ID',
            field=models.AutoField(db_column='a_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_NAME',
            field=models.CharField(db_column='a_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_PATRONYMIC',
            field=models.CharField(db_column='a_patronymic', max_length=50),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_SURNAME',
            field=models.CharField(db_column='a_surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='A_TEL',
            field=models.CharField(db_column='a_tel', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='E_COUNT',
            field=models.IntegerField(db_column='e_count'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='E_ID',
            field=models.AutoField(db_column='e_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='E_NAME',
            field=models.CharField(db_column='e_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='L_ID',
            field=models.ForeignKey(db_column='l_id', on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='P_ID',
            field=models.OneToOneField(db_column='p_id', on_delete=django.db.models.deletion.CASCADE, to='api.passport'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='T_TYPE',
            field=models.ForeignKey(db_column='t_type', on_delete=django.db.models.deletion.CASCADE, to='api.equipment_type'),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_CAPACITY',
            field=models.DecimalField(blank=True, db_column='t_capacity', decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_HEIGHT',
            field=models.DecimalField(db_column='t_height', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_LENGTH',
            field=models.DecimalField(db_column='t_length', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_LIFE',
            field=models.IntegerField(db_column='t_life'),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_PRICE',
            field=models.DecimalField(db_column='t_price', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_TYPE',
            field=models.CharField(db_column='t_type', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_WEIGHT',
            field=models.DecimalField(db_column='t_weight', decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='equipment_type',
            name='T_WIDTH',
            field=models.DecimalField(db_column='t_width', decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='location',
            name='L_AREA',
            field=models.CharField(db_column='l_area', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='L_ID',
            field=models.AutoField(db_column='l_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='L_SHOP',
            field=models.CharField(db_column='l_shop', max_length=30),
        ),
        migrations.AlterField(
            model_name='management_journal',
            name='A_ID',
            field=models.ForeignKey(db_column='a_id', on_delete=django.db.models.deletion.CASCADE, to='api.administrator'),
        ),
        migrations.AlterField(
            model_name='management_journal',
            name='E_ID',
            field=models.ForeignKey(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='management_journal',
            name='J_DATETIME',
            field=models.DateTimeField(db_column='j_datetime'),
        ),
        migrations.AlterField(
            model_name='management_journal',
            name='J_ID',
            field=models.AutoField(db_column='j_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='management_journal',
            name='J_TYPE',
            field=models.CharField(db_column='j_type', max_length=30),
        ),
        migrations.AlterField(
            model_name='passport',
            name='E_ID',
            field=models.IntegerField(blank=True, db_column='e_id', null=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='P_ID',
            field=models.AutoField(db_column='p_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passport',
            name='T_TYPE',
            field=models.ForeignKey(db_column='t_type', on_delete=django.db.models.deletion.CASCADE, to='api.equipment_type'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='E_ID',
            field=models.ForeignKey(db_column='e_id', on_delete=django.db.models.deletion.CASCADE, to='api.equipment'),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='R_ID',
            field=models.AutoField(db_column='r_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='U_ID',
            field=models.ForeignKey(db_column='u_id', on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_EMAIL',
            field=models.CharField(db_column='u_email', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_ID',
            field=models.AutoField(db_column='u_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_NAME',
            field=models.CharField(db_column='u_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_PATRONYMIC',
            field=models.CharField(db_column='u_patronymic', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_SURNAME',
            field=models.CharField(db_column='u_surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='U_TEL',
            field=models.CharField(db_column='u_tel', max_length=30),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
